name: Bug Report
description: Report a bug in SentinelGate
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? Provide a clear and concise description of the bug.
      placeholder: A clear description of the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Start SentinelGate with config...
        2. Send request to...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `sentinel-gate version`
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      options:
        - Docker
        - Binary
        - Source
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: OS
      description: Operating system and version
      placeholder: "e.g. Ubuntu 22.04, macOS 14, Windows 11"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (sensitive data redacted)
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (sensitive data redacted)
      render: yaml
    validations:
      required: false

  - type: checkboxes
    id: search
    attributes:
      label: Due Diligence
      options:
        - label: I have searched existing issues for duplicates
          required: true
